name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          sudo apt-get -qq update &&
          sudo apt-get install -y build-essential libtbb-dev ninja-build jq
      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh &&
          chmod u+x llvm.sh &&
          sudo ./llvm.sh 18 all &&
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-18 100 &&
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-18 100 &&
          echo /usr/lib/llvm-18 >> $GITHUB_PATH
      - name: Install CMake
        uses: lukka/get-cmake@v3.31.6
      - name: Install Vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'd5ec528843d29e3a52d745a64b469f810b2cedbf'
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-vcpkg'
          buildPreset: 'ninja-vcpkg-release'
          testPreset: 'ninja-vcpkg-test-release'
          testPresetAdditionalArgs: "['--output-on-failure','--verbose']"
      - name: Set Version
        if: github.ref == 'refs/heads/main'
        run: |
          echo "SPORE_VERSION=$(bash .github/scripts/get_version.sh)" >> $GITHUB_ENV
      - name: Tag Version
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "${GITHUB_ACTOR}" &&
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" &&
          $(echo -n $SPORE_VERSION > VERSION) &&
          git checkout -B releases/v${SPORE_VERSION%.*.*} &&
          git add VERSION &&
          git commit -m "chore: Update version to v$SPORE_VERSION" &&
          git tag -af v$SPORE_VERSION -m "Auto-generated semantic tag v$SPORE_VERSION" &&
          git push --set-upstream origin releases/v${SPORE_VERSION%.*.*} --force &&
          git push origin v$SPORE_VERSION --force
      - name: Checkout Vcpkg Repository
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v2
        with:
          repository: sporacid/spore-vcpkg
          path: .spore-vcpkg
          fetch-depth: 0
      - name: Update Vcpkg
        if: github.ref == 'refs/heads/main'
        run: |
          sh .spore-vcpkg/scripts/update-version.sh spore-meta $SPORE_VERSION $(git rev-list -n 1 v$SPORE_VERSION)